examples/data/ldcE.ts
examples/data/ldcP.ts
examples/data/planningPermission.ts
examples/validLawfulDevelopmentCertificateExisting.json
examples/validLawfulDevelopmentCertificateProposed.json
examples/validPlanningPermission.json
schema/schema.json
types/schema/data/Proposal.ts

chore: better `data.proposal.details` examples

---

schema/schema.json
types/enums/ApplicationTypes.ts

via feedback from August https://opensystemslab.slack.com/archives/C5Q59R3HB/p1699026559654489

fix: add missing Prior Approval `ApplicationType`

---

schema/schema.json
types/enums/ApplicationTypes.ts

per BOPS feedback here https://opendigitalplanning.slack.com/archives/C0634B4B8TT/p1700147689379169

chore: add `pp.full.major` & `pp.full.minor` `ApplicationTypes`

---

package.json
pnpm-lock.yaml

Resolves https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/4

fix: CVE-2024-23331

---

examples/data/ldcE.ts
examples/data/ldcP.ts
examples/data/planningPermission.ts
examples/data/priorApproval.ts
schema/schema.json
types/schema/Metadata.ts

- Adds a list of requested files in `service.metadata.files`

feat: Add `RequestedFiles` (v1)

---

v0.2.0/examples/validLawfulDevelopmentCertificateExisting.json
v0.2.0/examples/validLawfulDevelopmentCertificateProposed.json
v0.2.0/examples/validPlanningPermission.json
v0.2.0/examples/validPriorApproval.json
v0.2.1/examples/validLawfulDevelopmentCertificateExisting.json
v0.2.1/examples/validLawfulDevelopmentCertificateProposed.json
v0.2.1/examples/validPlanningPermission.json
v0.2.1/examples/validPriorApproval.json
v0.2.2/examples/validLawfulDevelopmentCertificateExisting.json
v0.2.2/examples/validLawfulDevelopmentCertificateProposed.json
v0.2.2/examples/validPlanningPermission.json
v0.2.2/examples/validPriorApproval.json
v0.2.3/examples/validLawfulDevelopmentCertificateExisting.json
v0.2.3/examples/validLawfulDevelopmentCertificateProposed.json
v0.2.3/examples/validPlanningPermission.json
v0.2.3/examples/validPriorApproval.json
v0.3.0/examples/validLawfulDevelopmentCertificateExisting.json
v0.3.0/examples/validLawfulDevelopmentCertificateProposed.json
v0.3.0/examples/validPlanningPermission.json
v0.3.0/examples/validPriorApproval.json

Bug spotted by BOPS :bug:  
- This PR retroactively corrects previous releases
- I'll open a second PR against main to update the GitHub action publishing script for future releases

fix: replace `@next` with correct version across dist examples

---

types/enums/FileTypes.ts

Add the support of `Viability Appraisal` file type

Add Viability Appraisal filetype

---

schema/schema.json
types/enums/FileTypes.ts

Fixes failed staging app validation https://planx.airbrake.io/projects/329753/groups/3756932628981323002

chore: update `FileTypes` enum

---

schema/schema.json
types/enums/ApplicationTypes.ts

There are different determination periods for minor outline applications vs. major outline applications (8 weeks vs. 13 weeks).

Split outline application types into minor/major

---

examples/data/ldcE.ts
examples/data/ldcP.ts
examples/data/planningPermission.ts
examples/validLawfulDevelopmentCertificateExisting.json
examples/validLawfulDevelopmentCertificateProposed.json
examples/validPlanningPermission.json
schema/schema.json
types/schema/Metadata.ts
types/schema/data/Application.ts

Based on output of https://editor.planx.uk/opensystemslab/fee-calculator-new

chore: better document `ApplicationFee` categories and update existing examples

---

CHANGELOG.md
package.json

Reverts theopensystemslab/digital-planning-data-schemas#166

Revert "v0.6.0"

---

types/enums/ApplicationTypes.ts

removed incorrect variable 'nonMaterial.amendment' and added the two new 'amendment.minorMaterial' and 'amendment.nonMaterial'

George/Amend a planning permission/Update ApplicationTypes.ts

---

pnpm-lock.yaml

Fixes https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/6

fix: CVE-2024-4068

---

schema/schema.json
types/enums/ApplicationTypes.ts

Continuing to work through new services & payloads here https://www.notion.so/opensystemslab/Payloads-Schema-Updates-8e632d514b004291a4b6d3f8eb08f6bb

chore: sync latest `ApplicationTypes`

---

examples/data/landDrainageConsent.ts
examples/landDrainageConsent.json
schema/schema.json
scripts/build-json-examples.ts
tests/usage.test.ts
types/enums/FileTypes.ts
types/enums/ProjectTypes.ts
types/schema/data/Applicant.ts
types/schema/data/Application.ts
types/schema/data/Proposal.ts

Based on https://editor.planx.dev/templates/apply-for-land-drainage-consent & example notes here https://www.notion.so/opensystemslab/Payloads-Schema-Updates-8e632d514b004291a4b6d3f8eb08f6bb

feat: Land Drainage Consent example payload and associated types

---

schema/schema.json
types/enums/ApplicationTypes.ts

Per feedback here https://opensystemslab.slack.com/archives/C5Q59R3HB/p1720687068455179?thread_ts=1720682619.326789&cid=C5Q59R3HB

feat: update missing descriptions for Prior Approval `ApplicationTypes`

---

schema/schema.json
types/enums/ApplicationTypes.ts

One minor correction spotted by Planx services team - last change going into #199 !

fix: remove `pp.pip.technicalDetails` ApplicationType, now part of `pp.full` journey

---

types/schemas/prototypeApplication/enums/PropertyTypes.ts

Converts PropertyType from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.

chore: `PropertyType` enum

---

types/schemas/prototypeApplication/enums/ProjectType.ts

Converts `ProjectType` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.

chore: `ProjectType` enum

---

types/schemas/prototypeApplication/data/shared.ts
types/schemas/prototypeApplication/enums/PlanningDesignation.ts

Converts `PlanningDesignation` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.

chore: `PlanningDesignation` enum

---

types/schemas/prototypeApplication/enums/FileType.ts

Converts `FileType` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.

chore: `FileType` enum

---

schemas/prototypeApplication.json
types/schemas/prototypeApplication/data/Proposal.ts
types/schemas/prototypeApplication/index.ts

So we can have an easy before/after to share for further feedback with Idox - see context https://opensystemslab.slack.com/archives/C01E3AC0C03/p1723031053626499

chore: add a mock field to demonstrate how new simplified enums are generating

---

schemas/prototypeApplication.json
types/schemas/prototypeApplication/data/ApplicationData.ts
types/schemas/prototypeApplication/data/Property.ts
types/schemas/prototypeApplication/data/Proposal.ts

Remove references to "UK" in favor of "England", which better matches the scope of our definitions and external data dependences (eg Planning Data "regions")

fix: `prototypeApplication` should specify "England" rather than "UK"

---

package.json
pnpm-lock.yaml

Resolves - 
- https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/7
- https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/8
- https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/9

chore: Bump vitest

---

schemas/application.json
schemas/prototypeApplication.json
types/schemas/application/enums/ApplicationTypes.ts
types/schemas/prototypeApplication/enums/ApplicationType.ts

Fixes #249
Thanks for flagging this typo / dupe !

fix: Correct `pp.outline.major.some.waste` application type description

---

.github/workflows/push.yml

Reverts theopensystemslab/digital-planning-data-schemas#258

Revert "fix: remove flag for frozen lockfile"

---

docs/package.json
docs/vite.config.ts

Reverts theopensystemslab/digital-planning-data-schemas#259

Revert "Add homepage path to config files"

---

docs/README.md

Reverts theopensystemslab/digital-planning-data-schemas#260

Revert "docs: add deployment explanation to schema viewer readme"

---

README.md

docs: add link to schema viewer in readme

---

.gitignore
package.json
pnpm-lock.yaml
schemas/application.json
schemas/preApplication.json
schemas/prototypeApplication.json

Rolls back TS to a previous version due to build errors on `main`

chore: Rollback TS version due to build errors

---

v0.7.2/schemas/application.json
v0.7.2/schemas/preApplication.json

Add dist files for v0.7.2

---

types/schemas/postSubmissionApplication/data/CaseOfficer.ts

I forgot to export case officer type 🤦‍♀️

PostSubmission export case officer type

---

IMPLEMENTATION.md
schemas/postSubmissionApplication.json
types/schemas/postSubmissionApplication/data/Comment.ts

Updating API implementation documentation with fields that actually exist!

Updating comment endpoint API implementation documentation 

---

pnpm-lock.yaml

Regenerated lockfile to fix - 
- https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/22
- https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/23

fix: CVE-2025-5889

---

schemas/postSubmissionApplication.json
schemas/postSubmissionPublishedApplication.json
types/schemas/postSubmissionApplication/data/SpecialistComment.ts

[Ticket 1553](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-1553)

Make organisation specialism optional in SpecialistBase
