- examples/data/ldcE.ts
- examples/data/ldcP.ts
- examples/data/planningPermission.ts
- examples/data/priorApproval.ts
- examples/validLawfulDevelopmentCertificateExisting.json
- examples/validLawfulDevelopmentCertificateProposed.json
- examples/validPlanningPermission.json
- examples/validPriorApproval.json
- schema/schema.json
- tests/usage.test.ts
- types/schema/data/Applicant.ts
Emily spotted this one today while we were catching up about this work and how it relates to what editors define!
Removes `data.applicant.contact` & `data.applicant.agent.contact` and bumps keys like `name`, `email`, `phone`, `company` out to the main level consistent with Planx passport heirarchy. There wasn't any particularly good reason to wrap within `contact` in the first place. 
Once merged and published, I'll update migration guides accordingly (it's unlikely anyone has started parsing yet).
> fix: update `Applicant` definition

- schema/schema.json
- types/schema/Metadata.ts
- types/schema/Responses.ts
- `url` is proper `URL` type, rather than `string`
- `text` is always required if `policyRef` is available (might be case for `url` too once examples are updated? but not sure this is actually a planx content requirement!)
> fix: better type for Responses `policyRef`

- examples/data/ldcE.ts
- examples/data/ldcP.ts
- examples/data/planningPermission.ts
- examples/data/priorApproval.ts
- examples/validLawfulDevelopmentCertificateExisting.json
- examples/validLawfulDevelopmentCertificateProposed.json
- examples/validPlanningPermission.json
- examples/validPriorApproval.json
- Update `responses` to include `url` of `policyRefs`
- Update `data.property.planning.source` to include correct URL to refetch
> chore: update example payloads

- examples/data/ldcE.ts
- examples/data/ldcP.ts
- examples/data/planningPermission.ts
- examples/data/priorApproval.ts
- examples/validLawfulDevelopmentCertificateExisting.json
- examples/validLawfulDevelopmentCertificateProposed.json
- examples/validPlanningPermission.json
- examples/validPriorApproval.json
- schema/schema.json
- types/schema/Metadata.ts
Sourced from `reference` property here https://www.planning.data.gov.uk/entity.json?dataset=local-authority&limit=500
This [specification](https://digital-land.github.io/specification/specification/planning-application/) cites "reference code", but I'm honestly not exactly sure how I'd format this as a CURIE in JSON Schema - but this string should be a better alignment for now?
See #53 
I'll open a corresponding Planx PR to decide how to deal with this there: fetch & store at same point we get `local-authority-district` or store statically within `teams` db table & query with other metadata in planx-core?
> fix: update organisation to align to Planning Data reference code

- examples/validLawfulDevelopmentCertificateExisting.json
- examples/validLawfulDevelopmentCertificateProposed.json
- examples/validPlanningPermission.json
- examples/validPriorApproval.json
- schema/schema.json
- types/schema/data/Applicant.ts
- types/schema/data/Property.ts
- types/schema/data/Proposal.ts
Two small tweaks:
- `noticeReason` was requested from BOPS here https://opendigitalplanning.slack.com/archives/C0182MVK4AW/p1700148320500969
- Boundary descriptions better describe our new data sources now! We'll still only be populating `proposal.boundary` until title's are "live" on Planx
> fix: add `data.applicant.ownership.noticeReason` and describe `data.property.boundary` & `data.proposal.boundary`

- package.json
- pnpm-lock.yaml
Replaces https://github.com/theopensystemslab/digital-planning-data-schemas/pull/91 and resolves https://github.com/theopensystemslab/digital-planning-data-schemas/security/dependabot/3
Docs for v1 release - https://github.com/vitest-dev/vitest/releases/tag/v1.0.0
Nothing too scary or obviously breaking here - tests all pass locally and on CI 👌
> chore: Bump vitest to v1

- schema/schema.json
- types/enums/FileTypes.ts
Found while updating BOPS v1 tagging
> fix: correct typo in `FileTypes`

- .github/workflows/publish.yml
I think this should work, but admittedly haven't tried queuing up a release to test it ! Ideas ofr testing locally, or we just test on next release?
See #114
If this doesn't work, we can alternatively try editing `scripts/build-json-examples.ts` - but this script isn't currently aware of the current schema version (`$id`), which differs from package.json version - so felt like the more complicated route.
> fix: add step to Github Action publish workflow to update version across example files

- schema/schema.json
- types/schema/Metadata.ts
An alternative enum approach to #118 - no strong opinions, up for discussion ! 
The enum perhaps offers a slightly more clear "default" state as asked here https://github.com/theopensystemslab/digital-planning-data-schemas/issues/117#issuecomment-1941625221. "Any" very much feels like a placeholder until another user comes along and defines their own proper metadata (eg `'Any' | 'PlanX' | 'PlanningPortal'`)
Fixes #117
> fix: require `metadata.source` for any provider, not only Planx

- examples/data/ldcE.ts
- examples/data/priorApproval.ts
- schema/schema.json
- types/schema/data/Property.ts
Per feedback from BOPS, see thread: https://opendigitalplanning.slack.com/archives/C0634B4B8TT/p1707994154106899
`text` & `url` naming convention aligns to "policyRefs" in `responses`
> chore: adjust `planning.designations.entities` "source" to include text and url

- .husky/pre-commit
- examples/validLawfulDevelopmentCertificateExisting.json
- examples/validLawfulDevelopmentCertificateProposed.json
- examples/validPlanningPermission.json
- examples/validPriorApproval.json
- schema/schema.json
Our examples & schema are correct in `dist` & in `/examples/data` on `main`, but the _generated_ examples and schema.json on `main` can fall out of sync with CI tests still passing if you simply forget to run either of these commands manually before pushing your changes (see #131) - too easy to forget & causing confusion with consumers!
This adds `pnpm build-json-examples` & `pnpm build-schema:dev` commands to the pre-commit hook if the branch is _not_ `main`. This should keep all files on main tagged at the `@next` version, and _not_ impact the Github Actions workflow for publishing from `main` to `dist` with a correct published version number.
> chore: add steps to pre-commit hook to build json examples & dev schema

- schema/schema.json
- types/schema/data/Property.ts
- types/schema/data/Proposal.ts
- types/schema/data/shared.ts
See rows 150-165 in `Apply for Planning Permission (Householder)` tab https://docs.google.com/spreadsheets/d/1ePihRD37-2071Wq6t2Y7QtBt7juySWuVP6SAF6T-0vo/edit#gid=1188278375
`shared.ts` file introduced here will hold definitions that are repeated between `property` & `proposal`. Parking and others are going to be similarly organised this way soon.
> feat: add types for existing & proposed `Materials`

- .github/workflows/publish.yml
Ensuring that `examples` have proper version numbers when published to `/dist` was fixed via #131, this is tidying up an earlier attempt that didn't actually work!
> fix: remove unused steps in Github Action publish workflow

- schema/schema.json
- types/enums/ProjectTypes.ts
Two `ProjectTypes` related bugs that have been raised in recent testing:
- `not` prefixed values will eventually be dropped once new SetValue functionality is implemented, but we should support them in the meantime as long as they still exist in service content
- Lambeth's testing on Friday hit the `changeOfUse.annexe` typo and I updated staging session data directly to succesfully resubmit in the interim until we have a more thorough next release
> fix: missing or incorrect `ProjectTypes` values

- schema/schema.json
- types/enums/ProjectTypes.ts
Synced from:
- Planx service content https://editor.planx.uk/opensystemslab/listed-building-consent-more-information
- "Project Types" tab here https://docs.google.com/spreadsheets/d/1ePihRD37-2071Wq6t2Y7QtBt7juySWuVP6SAF6T-0vo/edit#gid=389104115
> feat: add `ProjectTypes` support by Listed Building Consent journeys

- schema/schema.json
- types/schema/data/Proposal.ts
Quick fix! I think this is technically a breaking change if anybody is using the types from this repo, but not the schema itself.
> chore: Typo in `ProtectedSpaceDesignation`

- schema/schema.json
- types/enums/ApplicationTypes.ts
Despite the [standard form][1] combining both types of tree works they follow different workflows - trees with a Tree Preservation Order (TPO) is an [application for consent][2] whereas trees in a Conservation Area (CA) is a [notification of intended works][3].
The process for trees with a TPO takes eight weeks and the process for trees in a CA is six weeks. Trees in a conservation area with an existing TPO follow the standard procedure.
[1]: https://assets.publishing.service.gov.uk/media/5b06c81de5274a1c5490ce6f/Form031_england_en_revised__2_.pdf
[2]: https://www.gov.uk/guidance/tree-preservation-orders-and-trees-in-conservation-areas#making-applications-tpo
[3]: https://www.gov.uk/guidance/tree-preservation-orders-and-trees-in-conservation-areas#Protecting-trees-in-conservation-areas
> Split treeworksConsent into two separate types

- schema/schema.json
- types/schema/data/Applicant.ts
Based on recent service changes here https://editor.planx.uk/opensystemslab/ownership
> chore: update `Ownership` to include additional details asked for in Planning Permission & LBC services

- schema/schema.json
- types/schema/Metadata.ts
- types/schema/data/Application.ts
Based on service changes queued up here https://editor.planx.uk/opensystemslab/fee-calculator-new
> feat: add breakdown by planning fee catogories to `ApplicationFee` & `FeeExplanation` 

- schema/schema.json
- types/schema/data/Property.ts
Because the Greater London Authority (aka `london-data-hub` service) reporting requirements don't apply consistently to all application types - eg Listed Building Consent applicants will _not_ be asked about their property's title number or EPC status.
See thread https://opensystemslab.slack.com/archives/C5Q59R3HB/p1714492246639809
> fix: all `LondonProperty` fields should be optional besides "region"

- schema/schema.json
- types/schema/Metadata.ts
- types/schema/data/Application.ts
For example, Listed Building Consent applications will not have fee, and therefore applicants also won't answer questions related to exemptions or reductions. Without this, we'd require the payload displays fee = 0 and `false` exemptions/reductions which isn't entirely accurate since those questions were never encountered.
A future improvement would be to scope / connect this type directly to the applicable `ApplicationTypes` - but let's introduce more generally at first.
> feat: add `ApplicationFeeNotApplicable` union type to indicate when no costs apply

- examples/data/listedBuildingConsent.ts
- examples/validListedBuildingConsent.json
- scripts/build-json-examples.ts
- tests/usage.test.ts
Based on test application here https://api.editor.planx.dev/admin/session/0f2abdbd-2ec5-4918-979b-123bd856b94f/digital-planning-application?skipValidation=true (using Blue Plaque address in Camden)
LBC applications capture a couple new things:
- Fee "not applicable"
- No `preAssessment`
- New ownership types, including agricultural tenants and discrete declaration
- New project types
- Sites in London are not subject to extra Greater London Authority reporting requirements for this application type
Otherwise should feel very familar!
> feat: add an example payload from `apply-for-listed-building-consent` service

- examples/data/ldcE.ts
- examples/data/ldcP.ts
- examples/data/listedBuildingConsent.ts
- examples/data/planningPermission.ts
- examples/validLawfulDevelopmentCertificateExisting.json
- examples/validLawfulDevelopmentCertificateProposed.json
- examples/validListedBuildingConsent.json
- examples/validPlanningPermission.json
- schema/schema.json
- types/schema/data/Applicant.ts
Based on feedback from August about recent service changes to how Planx collects ownership info.
- Moves `data.applicant.interest` &rarr; `data.applicant.ownership.interest` for more meaningful heirarchy
- Updates example payloads to reflect changes to ownership service https://editor.planx.uk/opensystemslab/ownership
- LDCs no longer set `certificate`
- LDCs no longer report the `noticeDate` for individual owners, but simply if `noticeGiven` (boolean) and, if false,  `noNoticeReason` (string)
- Planning Permission & LBC assign a certificate and ask more detailed questions about agricultural tenants, publishing of notice, and a declaration
> fix: `Ownership` should include `interest` plus updated example payloads

- .github/workflows/publish.yml
Hoping this fixes error on latest action run https://github.com/theopensystemslab/digital-planning-data-schemas/actions/runs/8983467713/job/24673409957
Package JSON & lockfile don't need to be published to `dist` branch anyways, so should be okay?
> fix: stash pnpm lockfile in publish workflow

- .github/workflows/publish.yml
Reverts theopensystemslab/digital-planning-data-schemas#169
This fixed v0.6.0 release - but hoping we don't actually need this line going forward so going to revert ! 
Can always repeat if we see again.
> Revert "fix: stash pnpm lockfile in publish workflow"

- schema/schema.json
- types/Schema.ts
- types/enums/ApplicationTypes.ts
- types/enums/FileTypes.ts
- types/schema/data/Files.ts
- types/schema/data/Property.ts
- types/schema/data/Proposal.ts
- types/schema/data/shared.ts
For certain supported file types, Planx is beginning to offer applicants an option to provide the necessary information by uploading a document _or_ by answering a set of structured questions equivalent to the contents of the traditional physical document.
Currently, if the user choses the question route, those answers are exclusively being passed along via the `responses` section of the schema. But we want to make them easier to parse for reporting, so this introduces a _new_ optional `data.files` key.
Based on these Planx services:
- https://editor.planx.uk/opensystemslab/design-and-access-statement-form,mQQItUM4m0
- https://editor.planx.uk/opensystemslab/heritage-statement-form,r5w5NAGZvv
> feat: support files submitted as "data"

- schema/schema.json
- types/enums/ApplicationTypes.ts
Based on service team notes/updates tracked here https://www.notion.so/opensystemslab/Payloads-Schema-Updates-8e632d514b004291a4b6d3f8eb08f6bb
We don't have nice "plain english" names for all the Prior Approvals yet, but seems best they get added to the list ASAP regardless for "completeness".
> chore: update `ApplicationTypes`

- examples/data/planningPermission/minor.ts
- examples/planningPermission/minor.json
- schema/schema.json
- scripts/build-json-examples.ts
- tests/usage.test.ts
- types/enums/FileTypes.ts
- types/schema/data/Property.ts
- types/schema/data/Proposal.ts
- types/schema/data/shared.ts
Relies on #192 
Adds a Minor Planning Permission example for a site within the UK. 
Another Minor example for a GLA site coming soon in a followup PR :+1:
> feat: Minor Planning Permission example payload

- examples/data/planningPermission/major.ts
- examples/data/planningPermission/minor.ts
- examples/data/priorApproval/buildHomes.ts
- examples/planningPermission/major.json
- examples/planningPermission/minor.json
- examples/priorApproval/buildHomes.json
- schema/schema.json
- scripts/build-json-examples.ts
- tests/usage.test.ts
- types/enums/FileTypes.ts
- types/schema/data/Property.ts
- types/schema/data/Proposal.ts
- types/schema/data/shared.ts
Relies on #192 
Adds a Major Planning Permission example (non-London) plus a few related type adjustments/additions!
> feat: Major Planning Permission example payload

- examples/data/lawfulDevelopmentCertificate/existing.ts
- examples/data/listedBuildingConsent.ts
- examples/data/priorApproval/convertCommercialToHome.ts
- examples/data/priorApproval/extendUniversity.ts
- examples/lawfulDevelopmentCertificate/existing.json
- examples/listedBuildingConsent.json
- examples/priorApproval/convertCommercialToHome.json
- examples/priorApproval/extendUniversity.json
- schema/schema.json
- types/enums/PlanningConstraints.ts
- types/schema/data/Property.ts
Per feedback https://github.com/theopensystemslab/digital-planning-data-schemas/pull/192#discussion_r1663738433
> fix: for intersecting planning constraints, allow `entities` to be optional in favor of more specific type

- .github/workflows/publish.yml
- Fixes an issue identified on [most recent production deploy](https://github.com/theopensystemslab/digital-planning-data-schemas/actions/runs/9904681601/job/27362608050)
- Copies JSON examples recursively, preserving folder structure
- Removed source JSON files, generated by `pnpm build`
Tested locally, see results in `/daf` folder below -
> fix: Update 'Build and move files' step to preserve new example folder structure

- .eslintrc.json
- .github/workflows/publish.yml
- On publish of a new version, also copy the schemas, examples, and types to `/latest`
- This means we get a stable URL always pointing to the latest published version at `https://theopensystemslab.github.io/digital-planning-data-schemas/lastest/schema/${schema}.json`
- Relies on https://github.com/theopensystemslab/digital-planning-data-schemas/pull/206
> feat: Add `/latest` directory containing most recently published version

- .eslintrc.json
- .github/workflows/update-next.yml
- Adds a new GitHub action which runs on merge to `main`
- This action syncs the state of `main` to the `@next` folder on the dist branch, meaning we can check the state of main via the url `https://theopensystemslab.github.io/digital-planning-data-schemas/@next/schema/${schema}.json`
- Relies on #204
> feat: Publish @next release on merge to `main`

- .github/workflows/publish.yml
- .github/workflows/update-next.yml
- Fixes failures in CI after merging #205 and #207
- Creates the required folders (on the current branch - it already exists only on the `dist` branch)
> fix: Correctly setup `/latest` and `/next` folders

- .github/workflows/update-next.yml
Script now matches "publish" action more closely, folders are correctly generated before moving files.
> fix: Correctly setup folders for @next script

- .github/workflows/publish.yml
- .github/workflows/update-next.yml
- Lockfile changes are currently introduced when running `pnpm i`, which then causes the `git fetch` command to fail
- Add the `--frozen-lockfile` flag ([docs](https://pnpm.io/cli/install#--frozen-lockfile))
Note: This flag should be set to true by default in CI environments, but it certainly looks like this isn't quite working as expected in GitHub actions.
> chore: Add `--frozen-lockfile` flag to CI process

- schemas/digitalPlanningApplication.json
- types/schemas/digitalPlanningApplication/enums/ApplicationTypes.ts
We had a few lingering out of sync variables - now synced to [this tab](https://docs.google.com/spreadsheets/d/1ePihRD37-2071Wq6t2Y7QtBt7juySWuVP6SAF6T-0vo/edit?gid=814404181#gid=814404181) for consistent external communication
Also pulled in the typos specific to application types from #213
> chore: sync `ApplicationTypes` to Planx services spreadsheet

- .github/workflows/publish.yml
- .github/workflows/update-next.yml
- examples/application/data/planningPermission/fullHouseholderInConservationArea.ts
This action is currently failing due to the way generating new files and checking out dist is working. Adding the -f (force) flag resolves this.
> fix: Update `@next` GitHub action

- types/schemas/prototypeApplication/enums/UseClass.ts
Converts `GLAUseClass` from the old enum format to the new format, please see #218 for context.
> chore: `GLAUseClass` enum

- types/schemas/prototypeApplication/enums/ResidentialUnitType.ts
Converts `ResidentialUnitType` from the old enum format to the new format, please see #218 for context.
> chore: `ResidentialUnitType` enum

- types/schemas/prototypeApplication/enums/ProtectedSpaceDesignation.ts
Converts `ProtectedSpaceDesignation` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.
> chore: `ProtectedSpaceDesignation` enum

- types/schemas/prototypeApplication/enums/HousingProvider.ts
Converts `HousingProvider` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.
> chore: `HousingProvider` enum

- types/schemas/prototypeApplication/enums/DevelopmentType.ts
Converts `DevelopmentType` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.
> chore: `DevelopmentType` enum

- types/schemas/prototypeApplication/enums/OpenSpace.ts
Converts `OpenSpace` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.
> chore: `OpenSpace` enum

- types/schemas/prototypeApplication/enums/BuildingRegulation.ts
Converts `BuildingRegulation` from the old enum format to the new format, please see https://github.com/theopensystemslab/digital-planning-data-schemas/pull/218 for context.
> chore: `BuildingRegulation` enum

- schemas/prototypeApplication.json
- types/schemas/prototypeApplication/Metadata.ts
- types/schemas/prototypeApplication/data/Proposal.ts
- types/schemas/prototypeApplication/enums/PlanningDesignation.ts
- types/schemas/prototypeApplication/index.ts
PlanX fetches & suggestions administrative data to users throughout a service (eg planning constraints), and we always present users with an option to contest or change this data if it is outdated or not applicable.
If the user has chosen to override the suggested data, we want to ensure we still send planning officers both the original "source" data and the "user" override information for assessment and feedback.
This mocks up a proposed structure for sharing this !
> feat: define optional `overrides` on PlanX service metadata

- schemas/prototypeApplication.json
- types/schemas/prototypeApplication/data/Property.ts
Follows on from this PlanX change: https://github.com/theopensystemslab/planx-new/pull/3670
Also addresses Idox feedback that they expected to see support for address ranges more aligned with original OS source - so annotations hopefully help clarify how we map these ! 
`pao` remains the only required field, `paoEnd`, `sao`, and `saoEnd` are optional.
> chore: support site address ranges

- schemas/application.json
- schemas/prototypeApplication.json
- types/schemas/application/data/Applicant.ts
- types/schemas/prototypeApplication/data/Applicant.ts
Schema change to align with content. The correct term for a leaseholder with interest in land is lessee, not tenant. Agricultural tenants are a wholly separate issue and not affected by this fix.
> fix: change applicant ownership tenant to lessee

- docs/README.md
We have left this repo in a stable position for now, but the schema viewer is deployable. 
The README now explains how to deploy the viewer (though this unfortunately takes down the JSON files that are currently viewable).
> docs: add deployment explanation to schema viewer readme

- package.json
- pnpm-lock.yaml
It turns out that https://github.com/theopensystemslab/digital-planning-data-schemas/pull/253 was a breaking change - it relies on a particular version of node (or node types). We have the same issue [here](https://github.com/theopensystemslab/planx-core/pull/530) in planx-core which I spent a bit of time on but didn't quite get to the bottom of.
I think the answer is an update to Node v20 or v22 (due anyway!) across PlanX repos 👍 
On this branch I can run the pre-commit hook without issue.
> chore: Update lockfile, roll back TS version

- examples/application/data/landDrainageConsent.ts
- examples/application/landDrainageConsent.json
- schemas/application.json
- schemas/prototypeApplication.json
- types/schemas/application/data/Applicant.ts
- types/schemas/application/data/ApplicationData.ts
- types/schemas/application/data/Files.ts
- types/schemas/application/data/Property.ts
- types/schemas/application/data/Proposal.ts
- types/schemas/application/data/shared.ts
- types/schemas/application/enums/PlanningConstraints.ts
- types/schemas/preApplication/data/Applicant.ts
- types/schemas/preApplication/data/ApplicationData.ts
- types/schemas/preApplication/data/Property.ts
- types/schemas/preApplication/data/Proposal.ts
- types/schemas/prototypeApplication/data/Applicant.ts
- types/schemas/prototypeApplication/data/ApplicationData.ts
- types/schemas/prototypeApplication/data/Property.ts
- types/schemas/prototypeApplication/data/Proposal.ts
- types/schemas/prototypeApplication/data/shared.ts
- types/shared/Addresses.ts
- types/shared/Boundaries.ts
- types/shared/Constraints.ts
- types/shared/Contacts.ts
- types/shared/Declarations.ts
- types/shared/Fees.ts
- types/shared/Materials.ts
- types/shared/Ownership.ts
- types/shared/Regions.ts
Lots of refactors to the `/shared` types folder ! 
This one is big enough as-is, haven't touched the following yet but will in follow-up PRs: 
- Shared `enums`
- Resolve outstanding feedback & combine `application` & `prototypeApplication` into single `@next` `application`
- Review use of `@id` versus `@title` annotations (especially with docs viewer output)
> chore: refactor more `/shared` types

- schemas/application.json
- schemas/prototypeApplication.json
- types/schemas/application/data/ApplicationData.ts
- types/schemas/prototypeApplication/data/ApplicationData.ts
- types/shared/CommunityInfrastructureLevy.ts
**Key changes:**
- Moves type definitions to `/shared`
- Unions `NotLiable` path, `Liable` definitions don't change
**Comes from:**
- Latest PlanX service development here: https://editor.planx.uk/opensystemslab/community-infrastructure-levy-copy (see final Filter & CIL flagset)
- Lambeth's CIL feedback/request for PP pilot: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1733238460430359
> fix: update `CommunityIinfrastructureLevy` types to include "not liable" path

- pnpm-lock.yaml
- scripts/build-json-examples.ts
- scripts/build-schema.sh
- tests/usage.test.ts
- tsconfig.json
This PR does the following:
1. Rebuilds commit 5ddbba6 using the correct dependencies
2. Fixes some lint warnings
3. Ensures `build-schema` fails when a subprocess fails
4. Extracts `Entity` to a separate file to avoid duplicate definition
5. Ignores the build directory which contained `tsconfig.buildinfo`
6. Adds the preApplication schema to the usage tests
> Enable usage testing of the preApplication schema

- schemas/application.json
- schemas/preApplication.json
Realising that when I "accepted" the typo suggestions via the GitHub UI in #287, the `pnpm build-schema` pre-commit hook wouldn't have been triggered and I didn't manually make any further commits, so I failed to pick these typo corrections up in the actual built files ! Lesson learned !
Will open a separate PR to correct files on the `/dist` branch for v0.7.2 as well.
> fix: correct `pnpm build-schema` from main

- schemas/application.json
- schemas/prototypeApplication.json
- types/schemas/application/data/ApplicationData.ts
- types/schemas/prototypeApplication/data/ApplicationData.ts
New content only requires a reference (`application.preAppAdvice.reference`) if `application.preAppAdvice` is `true`.
> chore: adjust optional preApp info for applications

- schemas/application.json
- schemas/preApplication.json
- schemas/prototypeApplication.json
- types/schemas/application/data/Applicant.ts
- types/schemas/application/data/ApplicationData.ts
- types/schemas/application/data/Property.ts
- types/schemas/application/data/Proposal.ts
- types/schemas/prototypeApplication/data/Applicant.ts
- types/schemas/prototypeApplication/data/ApplicationData.ts
- types/schemas/prototypeApplication/data/Property.ts
- types/schemas/prototypeApplication/data/Proposal.ts
- types/shared/Addresses.ts
- types/shared/CommunityInfrastructureLevy.ts
- types/shared/Constraints.ts
- types/shared/Contacts.ts
- types/shared/Declarations.ts
- types/shared/Fees.ts
- types/shared/LinkedApplications.ts
- types/shared/MaintenanceContact.ts
- types/shared/Parking.ts
- types/shared/Regions.ts
- types/shared/SiteContact.ts
Only code re-organisations here, no functional changes! All examples still validate and tests pass. 
**Key changes:**
- Add `/shared` types for `Parking`, `MaintenanceContacts`, and `LinkedApplications`
- Update a number of `@title` annotations to drop `#` this is not required and a remnant of copying past `@id` (which do require `#`) to now `@title`
> chore: refactor more `/shared` type definitions

- examples/application/data/planningPermission/major.ts
- examples/application/planningPermission/major.json
- schemas/application.json
- schemas/preApplication.json
- schemas/prototypeApplication.json
- types/schemas/prototypeApplication/data/Applicant.ts
- types/shared/Ownership.ts
See context here https://opensystemslab.slack.com/archives/C089LL9LR5H/p1739544939178549
Brings schema definitions into sync with new "List" component schemas in PlanX https://github.com/theopensystemslab/planx-new/pull/4248
> chore: tweak `Ownership` definitions

- schemas/postSubmissionApplication.json
- types/schemas/postSubmissionApplication/data/Assessment.ts
Just a slight rework of the assessment section to make it easier to change parts of the process per application type in the future
> Update PostSubmissionAssessment 

- examples/prototypeApplication/advertConsent.json
- examples/prototypeApplication/data/advertConsent.ts
- schemas/application.json
- schemas/preApplication.json
- schemas/prototypeApplication.json
- types/schemas/prototypeApplication/data/Applicant.ts
- types/schemas/prototypeApplication/data/ApplicationData.ts
- types/schemas/prototypeApplication/data/Property.ts
- types/schemas/prototypeApplication/data/Proposal.ts
- types/schemas/prototypeApplication/enums/FileType.ts
- types/schemas/prototypeApplication/index.ts
Edited the Applicant, Proposal, ApplicationData, Property types. Added extra filetype to accommodate AdvertConsent application.
> Add AdvertConsent schema

- IMPLEMENTATION.md
- README.md
- types/schemas/postSubmissionApplication/implementation/ApiResponse.ts
- types/schemas/postSubmissionApplication/implementation/Pagination.ts
[Read it here](https://github.com/theopensystemslab/digital-planning-data-schemas/blob/hn/api-implementation-documentation/IMPLEMENTATION.md)!
This PR is to accompany the issue I raised here a while back (https://github.com/theopensystemslab/digital-planning-data-schemas/issues/296) I've stuck to just using markdown for now, following a "swagger-like" structure but I'm happy to switch to a different library or validator tool if there are any suggestions. 
I've based the documentation on:
* the endpoints we're currently using from BOPS
* the endpoints we will be changing in BOPS 
* The [DPR prototype](https://public-index-design-40bd5591d858.herokuapp.com/) designs which are currently being updated
* What I originally wrote in this issue: …
> API Implementation Documentation

- types/schemas/postSubmissionApplication/implementation/ApiResponse.ts
- types/schemas/postSubmissionApplication/implementation/Pagination.ts
I didn't notice that I had included ApiResponse twice in my other PR. 🤦‍♀️
This PR 
* removes duplicate ApiResponse from Pagination.ts file
* updates ApiResponse in ApiResponse file to include description
> Fix for duplicate ApiResponse type

- schemas/application.json
- schemas/postSubmissionApplication.json
- schemas/preApplication.json
- schemas/prototypeApplication.json
- types/shared/Constraints.ts
Will fetch and populated based on source data here: https://www.planning.data.gov.uk/dataset/battlefield
Comes by request of Tewkesbury, battlefields don't impact PD rights but they are of interest during assessment
> feat: add `battlefield` to `PlanningDesignations` enum

- IMPLEMENTATION.md
- types/schemas/postSubmissionApplication/implementation/Pagination.ts
Updates the pagination to clarify totalResults vs totalItems. I have set totalItems to be optional since its not always feasible to calculate this value.
> Update pagination structure to include totalResults and totalItems fields

- IMPLEMENTATION.md
Just updating the docs with the latest information.
[This branch](https://github.com/theopensystemslab/digital-planning-data-schemas/tree/hn/typebox-and-openapi) has more goodies but this stuff is the essentials for keeping this repo up to date.
> Implementation updates
